"""Auto-likes

Revision ID: b11d82d1c181
Revises: ea5fa14d82f6
Create Date: 2024-09-21 17:21:15.230732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11d82d1c181'
down_revision: Union[str, None] = 'ea5fa14d82f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['tb_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.add_column('tb_posts', sa.Column('is_published', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('tb_posts', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_column('tb_posts', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_posts', sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('tb_posts', 'rating')
    op.drop_column('tb_posts', 'is_published')
    op.drop_table('likes')
    # ### end Alembic commands ###
